name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.10'

    - name: Install uv and dependencies
      run: |
        curl -Ls https://astral.sh/uv/install.sh | sh
        uv venv                         # <--- добавлено создание виртуального окружения
        uv pip install .               # <--- установка зависимостей из pyproject.toml
        uv pip install pytest

    - name: Run tests
      run: |
        .venv/bin/pytest --junitxml=pytest-report.xml  # <--- указание на запуск из виртуального окружения

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest-report.xml

    - name: SonarCloud Analysis
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        organization: 'lawyer-arch'
        projectKey: 'lawyer-arch_car_dealer_parser'
        projectName: 'lawyer-arch_car_dealer_parser'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}